// nt.webclient/reactjs/nt/src/components/Pages/Login.js
import React, { Component } from "react";
import PropTypes from "prop-types";

const Login = () => {
  return (
    <div class='container'>
      <div class='col-md-12 min-vh-100 d-flex flex-column justify-content-center'>
        <div class='row'>
          <div class='col-lg-6 col-md-8 mx-auto'>
            <div class='card rounded shadow shadow-sm'>
              <div class='card-header'>
                <h3 class='mb-0'>Login</h3>
              </div>
              <div class='card-body'>
                <form className='form'>
                  <input type='text' name='username' placeholder='UserName' />
                  <input
                    type='password'
                    name='password'
                    placeholder='Password'
                  />
                  <input type='submit' value='Login' />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;

// nt.webclient/vuejs/nt/src/components/Login.vue
<template>
  <div class="card rounded shadow shadow-sm">
    <div class="card-header bg-primary">
      <div class="card-title">
        <h3 class="mb-0">Sign In</h3>
      </div>
    </div>
    <div class="card-body">
      <form class="form needs-validation">
        <input type="text" name="userName" placeholder="UserName" />
        <input type="password" name="passKey" placeholder="Password" />
        <input type="submit" value="Login" class="bg-primary btn-block" />
      </form>
      <div>Sign up</div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Login",
};
</script>

<style>
</style>
