// nt.webclient/reactjs/nt/src/pages/public/login.js
import React, { useState, useContext } from "react";
import UserContext from "../../context/user/userContext";
import ValidationMessage from "../../components/layout/validationMessage";
import { Link } from "react-router-dom";
import { useHistory } from "react-router-dom";
import { validateUser } from "../../api/user";

const Login = () => {
  const history = useHistory();

  const userContext = useContext(UserContext);
  const initialProfileValue = {
    userName: "",
    passKey: "",
  };
  const initialValidationMsg = {
    message: "",
    isVisible: false,
    isValid: false,
  };
  const [userProfile, setLoginProfile] = useState(initialProfileValue);
  const [validationMsg, setValidationMsg] = useState(initialValidationMsg);

  const onChange = async (e) => {
    setLoginProfile({ ...userProfile, [e.target.name]: e.target.value });
  };

  const onSubmit = async (e) => {
    e.preventDefault();

    const result = await validateUser(
      userProfile.userName,
      userProfile.passKey
    );

    if (result.hasError) {
      console.log("login error");
      console.log(result);

      setValidationMsg({
        isVisible: true,
        isValid: false,
        message: result.error, //errorMessage,
      });
    } else {
      const {
        isAuthenticated,
        token,
        userName,
        displayName,
        bio,
      } = result.data;

      if (isAuthenticated) {
        console.log("User Authenticated");
        userContext.setCurrentUser({
          authToken: token,
          currentUser: {
            userName: userName,
            displayName: displayName,
            bio: bio,
            rating: 5,
          },
          isAuthenticated: isAuthenticated,
        });
        console.log(history);
        history.push("/home");
        console.log("Redirecting...");
      }
    }
  };

  return (
    <div className='card rounded shadow shadow-sm'>
      <div className='card-header bg-primary'>
        <div className='card-title'>
          <h3 className='mb-0 '>Sign In</h3>
        </div>
      </div>
      <div className='card-body'>
        <form className='form needs-validation' onSubmit={onSubmit}>
          <input
            type='text'
            name='userName'
            placeholder='UserName'
            onChange={onChange}
          />
          <input
            type='password'
            name='passKey'
            placeholder='Password'
            onChange={onChange}
          />
          <input type='submit' value='Login' className='bg-primary btn-block' />
          <ValidationMessage
            isVisible={validationMsg.isVisible}
            isValid={validationMsg.isValid}
            message={validationMsg.message}
          />
        </form>
        <div>
          <Link to='/signup'>Sign up here</Link>
        </div>
      </div>
    </div>
  );
};

export default Login;

// nt.webclient/vuejs/nt/src/components/public/Login.vue
<template>
  <div class="card card-block rounded shadow shadow-sm">
    <div class="card-header bg-primary text-light text-uppercase">
      <div class="card-title align-middle">
        <h5 class="mb-0">Sign In</h5>
      </div>
    </div>
    <div class="card-body">
      <form class="form needs-validation" @submit="onSubmit">
        <div class="form-group">
          <input
            type="text"
            v-model="userName"
            v-bind:class="
              hasError('userName')
                ? 'form-control block is-invalid'
                : 'form-control block'
            "
            placeholder="Username"
          />
        </div>
        <div
          v-bind:class="
            hasError('userName') ? 'text-danger text-left' : 'd-none'
          "
        >
          <small>Username cannot be empty</small>
        </div>
        <div class="form-group">
          <input
            type="password"
            v-model="password"
            v-bind:class="
              hasError('password')
                ? 'form-control block is-invalid'
                : 'form-control block'
            "
            placeholder="Password"
          />
        </div>

        <div
          v-bind:class="
            hasError('password') ? 'text-danger text-left' : 'd-none'
          "
        >
          <small>Password cannot be empty</small>
        </div>

        <div class="form-group">
          <input
            type="submit"
            class="btn btn-block btn-primary"
            value="Submit"
          />
        </div>
        <div class="justify-content-center">
          <ValidationMessage
            v-bind:messages="serverMessage"
            v-bind:isError="hasServerError"
          />
        </div>
      </form>
      <div>
        Not a member ?
        <router-link to="/register">Sign up here</router-link>
      </div>
    </div>
  </div>
</template>

<script>
import { mapActions, mapGetters } from "vuex";
import { validateUser } from "../../api/user";
import ValidationMessage from "../../components/generic/ValidationMessage";
export default {
  name: "Login",
  components: { ValidationMessage },
  data() {
    return {
      errors: [],
      userName: "",
      password: "",
      serverMessage: [],
      hasServerError: false,
    };
  },
  computed: mapGetters(["currentUser"]),
  methods: {
    ...mapActions(["updateCurrentUser"]),
    hasError(key) {
      return this.errors.indexOf(key) != -1;
    },
    async onSubmit(e) {
      e.preventDefault();
      if (this.validateForm()) {
        var response = await validateUser(this.userName, this.password);

        if (response.hasError) {
          this.hasServerError = true;
          this.serverMessage = response.error;
          return;
        }

        this.updateCurrentUser({
          userName: response.data.userName,
          displayName: response.data.displayName,
          bio: response.data.bio,
          token: response.data.token,
        });

        console.log("User authenticated and updated, redirecting now..");
        this.$router.push("/p/dashboard");
      }
    },
    validateForm() {
      let isValidFlag = true;
      this.errors = [];

      if (!this.userName) {
        this.errors.push("userName");
        isValidFlag = false;
      }

      if (!this.password) {
        this.errors.push("password");
        isValidFlag = false;
      }
      return isValidFlag;
    },
  },
};
</script>

<style scoped></style>
