// client/nt.webclient/vue3/nt/src/pages/private/user/ChangePassword.vue
<template>
  <div class="container-fluid">
    <div class="row align-items-center justify-content-center">
      <div class="col-sm-8 col-md-6 col-lg-6">
        <div class="card">
          <div class="card-header font-weight-bold text-uppercase">
            Change Password
          </div>
          <div class="card-body">
            <form class="form needs-validation" v-on:submit="onSubmit">
              <div class="form-group">
                <label for="oldPassword">Old Password</label>
                <input
                  type="password"
                  v-model="oldPassword"
                  name="oldPassword"
                  v-bind:class="
                    hasError('oldPassword')
                      ? 'form-control block is-invalid'
                      : 'form-control block'
                  "
                />
              </div>

              <div class="d-flex justify-content-left">
                <ValidationMessage
                  v-bind:messages="oldPasswordError"
                  v-bind:isError="true"
                />
              </div>

              <div class="form-group">
                <label for="newPassword">New Password</label>
                <input
                  type="text"
                  name="newPassword"
                  v-model="newPassword"
                  v-bind:class="
                    hasError('newPassword')
                      ? 'form-control block is-invalid'
                      : 'form-control block'
                  "
                />
              </div>

              <div class="d-flex justify-content-left">
                <ValidationMessage
                  v-bind:messages="newPasswordError"
                  v-bind:isError="true"
                />
              </div>

              <div class="form-group">
                <label for="confirmPassword">Confirm Password</label>
                <input
                  type="text"
                  name="confirmPassword"
                  v-model="confirmPassword"
                  v-bind:class="
                    hasError('confirmPassword')
                      ? 'form-control block is-invalid'
                      : 'form-control block'
                  "
                />
              </div>

              <div class="d-flex justify-content-left">
                <ValidationMessage
                  v-bind:messages="confirmPasswordError"
                  v-bind:isError="true"
                />
              </div>

              <div class="form-group">
                <input
                  type="submit"
                  class="btn-primary"
                  value="Update Password"
                />
              </div>

              <div class="d-flex justify-content-left">
                <ValidationMessage
                  v-bind:messages="serverMessage"
                  v-bind:isError="hasServerError"
                />
              </div>

              <!-- <div class="form-group">
                <div v-bind:class="showServerMessage()">
                  <small>{{ this.serverMessage }}</small>
                </div>
              </div> -->
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";
import { changePassword } from "@/api/user";
import { minLength, isEquals } from "@/utils/validators.js";
import useValidator from "@/utils/inputValidators.js";
import ValidationMessage from "@/components/generic/ValidationMessage";

const serverMessage = ref([]);
const hasServerError = ref(false);
const oldPassword = ref("");
const newPassword = ref("");
const confirmPassword = ref("");
const errors = ref([]);

const onSubmit = async (e) => {
  e.preventDefault();
  errors.value = [];
  hasServerError.value = false;
  serverMessage.value = [];

  console.log(oldPassword.value);
  console.log(newPassword.value);
  console.log(confirmPassword.value);

  useValidator(oldPassword.value, [minLength(8)], (e) =>
    errors.value.push({ "oldPassword": e })
  );

  useValidator(newPassword.value, [minLength(8)], (e) =>
    errors.value.push({ "newPassword": e })
  );

  useValidator(
    confirmPassword.value,
    [minLength(8), isEquals(newPassword.value)],
    (e) => errors.value.push({ "confirmPassword": e })
  );

  if (errors.value.length == 0) {
    const response = await changePassword(
      oldPassword.value,
      newPassword.value
    );

    if (response.hasError) {
      hasServerError.value = true;
      serverMessage.value = response.error;
      return;
    }

    serverMessage.value.push("Password has been changed successfully.");
    console.log(serverMessage.value);
    console.log(response);
  }

  console.log(errors.value);
};

const hasError = (key) => {
  const result = errors.value.some((x) => key in x);
  return result;
};

const oldPasswordError = computed(() => {
  if (hasError("oldPassword")) {
    const result = errors.value.filter((x) => {
      if (x.oldPassword) {
        return true;
      }
      return false;
    });
    return result[0].oldPassword;
  }

  return [];
});

const newPasswordError = computed(() => {
  if (hasError("newPassword")) {
    const result = errors.value.filter((x) => {
      if (x.newPassword) {
        return true;
      }
      return false;
    });
    return result[0].newPassword;
  }

  return [];
});

const confirmPasswordError = computed(() => {
  if (hasError("confirmPassword")) {
    const result = errors.value.filter((x) => {
      if (x.confirmPassword) {
        return true;
      }
      return false;
    });
    return result[0].confirmPassword;
  }

  return [];
});

// const showServerMessage = () => {
//   if (!serverMessage.value) {
//     return "d-none justify-content-center";
//   }

//   return hasServerError.value
//     ? "text-danger justify-content-center"
//     : "text-success justify-content-center";
// }
</script>

<style></style>

// client/nt.webclient/reactjs/nt/src/pages/private/user/changePassword.js
import React, { useContext, useState } from "react";
import PropTypes from "prop-types";
import UserContext from "../../../context/user/userContext";
import ValidationMessage from "../../../components/layout/validationMessage";
import EditUserMenu, {
  CHANGE_PWD,
} from "../../../components/User/editUserMenu";
import { changePassword } from "../../../api/user";

const ChangePassword = ({ location }) => {
  const userContext = useContext(UserContext);
  const authToken = userContext.userToken;

  const [formValidation, setFormValidation] = useState({
    isVisible: false,
    isValid: true,
    message: "",
  });

  const { user } = location.state;
  const [userDetails, setUserDetails] = useState({
    oldPassword: "",
    newPassword: "",
    confirmPassword: "",
  });

  const onChange = (e) => {
    setUserDetails({ ...userDetails, [e.target.name]: e.target.value });
  };
  const onSubmit = async (e) => {
    e.preventDefault();

    const response = await changePassword(
      authToken,
      userDetails.oldPassword,
      userDetails.newPassword
    );
    validateResponse(response);
  };

  const validateResponse = (response) => {
    if (response.hasError) {
      setFormValidation({
        isValid: false,
        isVisible: true,
        message: response.error,
      });
    } else {
      setFormValidation({
        isValid: true,
        isVisible: true,
        message: ["Password changed successfully"],
      });
    }
  };

  return (
    <div className='container-fluid '>
      <div className='row'>
        <div className='col-lg-2'>
          <EditUserMenu user={user} selected={CHANGE_PWD} />
        </div>
        <div className='col-lg-10'>
          <div className='card'>
            <div className='card-header'>Change Password</div>
            <div className='card-body'>
              <form className='form needs-validation' onSubmit={onSubmit}>
                <p className='font-weight-bold'>Old Password</p>
                <input
                  type='password'
                  value={userDetails.oldPassword}
                  onChange={onChange}
                  name='oldPassword'
                />

                <p className='font-weight-bold'>New Password</p>
                <input
                  type='password'
                  name='newPassword'
                  value={userDetails.newPassword}
                  onChange={onChange}
                />

                <p className='font-weight-bold'>Confirm Password</p>
                <input
                  type='password'
                  name='confirmPassword'
                  value={userDetails.confirmPassword}
                  onChange={onChange}
                />

                <input type='submit' value='Update' />
                <ValidationMessage
                  isVisible={formValidation.isVisible}
                  message={formValidation.message}
                  isValid={formValidation.isValid}
                />
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

ChangePassword.propTypes = {
  location: PropTypes.object.isRequired,
};

export default ChangePassword;
