// nt.webclient/vuejs/nt/src/components/user/EditUserMenu.vue
<template>
  <ul className="list-group">
    <li>
      <router-link to="/edit" class="list-group-item">Edit Profile</router-link>
    </li>
    <li>
      <router-link to="/chpwd" class="list-group-item list-group-item-secondary"
        >Change Password</router-link
      >
    </li>
  </ul>
</template>

<script>
export default {
  name: "EditUserMenu",
};
</script>

<style scoped>
ui {
  list-style-type: none;
}

li {
  list-style: none;
}
</style>

// nt.webclient/reactjs/nt/src/components/User/editUserMenu.js
import React from "react";
import { Link } from "react-router-dom";
import PropTypes from "prop-types";

const EditUserMenu = ({ user, selected }) => {
  return (
    <ul className='list-group'>
      <li
        className={`list-group-item  ${
          selected === EDIT_PROFILE ? "list-group-item-secondary" : ""
        }`}
      >
        {" "}
        <Link to={{ pathname: "/edituser", state: { user: user } }}>
          Edit User Profile
        </Link>
      </li>
      <li
        className={`list-group-item  ${
          selected === CHANGE_PWD ? "list-group-item-secondary" : ""
        }`}
      >
        <Link to={{ pathname: "/changepassword", state: { user: user } }}>
          Change Password
        </Link>
      </li>
    </ul>
  );
};

EditUserMenu.propTypes = {
  user: PropTypes.object.isRequired,
  selected: PropTypes.string.isRequired,
};

export default EditUserMenu;
export const EDIT_PROFILE = "Edit Profile";
export const CHANGE_PWD = "Change Password";
