// nt.webclient/vuejs/nt/src/pages/private/user/ChangePassword.vue
<template>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2">
        <EditUserMenu />
      </div>
      <div class="col-sm-8 col-md-8 col-lg-10">
        <div class="card">
          <div class="card-header font-weight-bold text-uppercase">
            Change Password
          </div>
          <div class="card-body">
            <form class="form needs-validation" v-on:submit="onSubmit">
              <div class="form-group">
                <label for="oldPassword">Old Password</label>
                <input
                  type="password"
                  v-model="oldPassword"
                  name="oldPassword"
                  v-bind:class="
                    hasError('oldPassword')
                      ? 'form-control block is-invalid'
                      : 'form-control block'
                  "
                />
              </div>

              <div class="form-group">
                <label for="newPassword">New Password</label>
                <input
                  type="text"
                  name="newPassword"
                  v-model="newPassword"
                  v-bind:class="
                    hasError('newPassword')
                      ? 'form-control block is-invalid'
                      : 'form-control block'
                  "
                />
              </div>

              <div class="form-group">
                <label for="confirmPassword">Confirm Password</label>
                <input
                  type="text"
                  name="confirmPassword"
                  v-model="confirmPassword"
                  v-bind:class="
                    hasError('confirmPassword')
                      ? 'form-control block is-invalid'
                      : 'form-control block'
                  "
                />
              </div>

              <div class="form-group">
                <input type="submit" value="Update Password" />
              </div>
              <div class="form-group">
                <div v-bind:class="showServerMessage()">
                  <small>{{ this.serverMessage }}</small>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import EditUserMenu from "../../../components/user/EditUserMenu.vue";
import axios from "axios";
import { mapGetters } from "vuex";
export default {
  name: "ChangePassword",
  data() {
    return {
      authToken: "",
      oldPassword: "",
      newPassword: "",
      confirmPassword: "",
      errors: [],
      serverMessage: "",
      hasServerError: false,
    };
  },
  components: {
    EditUserMenu,
  },
  computed: mapGetters(["currentUser"]),
  created: function () {
    this.authToken = this.currentUser.token;
  },
  methods: {
    async onSubmit(e) {
      e.preventDefault();
      if (this.validateForm()) {
        console.log("Changing Password....");

        const headers = {
          "Access-Control-Allow-Headers": "*", // this will allow all CORS requests
          "Access-Control-Allow-Methods": "OPTIONS,POST,GET", // this states the allowed methods
          "Content-Type": "application/json", // this shows the expected content type
          Authorization: `Bearer ${this.authToken}`,
        };
        var updatedRecord = {
          oldPassword: this.oldPassword,
          newPassword: this.newPassword,
        };
        try {
          var response = await axios.post(
            "https://localhost:44353/api/User/ChangePassword",
            updatedRecord,
            { headers: headers }
          );

          console.log(response);
          if (response.data.hasError) {
            this.hasServerError = response.data.hasError;
            this.serverMessage = response.data.errorMessage;
            return;
          }

          this.hasServerError = false;
          this.serverMessage = "Password has been changed successfully.";
        } catch (error) {
          this.serverMessage = error.response.data.errors.NewPassword.shift();
          this.hasServerError = true;
          return;
        }
      }
    },
    hasError(key) {
      console.log(key + (this.errors.indexOf(key) != -1));
      return this.errors.indexOf(key) != -1;
    },
    validateForm() {
      let isValidFlag = true;
      this.errors = [];

      if (!this.newPassword) {
        this.errors.push("newPassword");
        isValidFlag = false;
      }

      if (!this.confirmPassword) {
        this.errors.push("confirmPassword");
        isValidFlag = false;
      }

      if (this.newPassword != this.confirmPassword) {
        this.errors.push("newPassword");
        this.errors.push("confirmPassword");
        isValidFlag = false;
      }

      return isValidFlag;
    },
    showServerMessage() {
      console.log(this.serverMessage);
      if (!this.serverMessage) {
        return "d-none justify-content-center";
      }

      return this.hasServerError
        ? "text-danger justify-content-center"
        : "text-success justify-content-center";
    },
  },
};
</script>

<style scoped>
input[type="text"],
input[type="email"],
input[type="password"],
input[type="date"],
select,
textarea {
  display: block;
  width: 100%;
  padding: 0.4rem;
  font-size: 1.2rem;
  border: 1px solid #ccc;
}

.form-group {
  align-items: left;
}
.form-group label {
  text-align: left;
  float: left;
}

.form-group small {
  text-align: center;
  float: none;
}
</style>

// nt.webclient/reactjs/nt/src/pages/private/user/changePassword.js
import React, { useContext, useState } from "react";
import PropTypes from "prop-types";
import Axios from "axios";
import UserContext from "../../../context/user/userContext";
import ValidationMessage from "../../../components/layout/validationMessage";
import EditUserMenu, {
  CHANGE_PWD,
} from "../../../components/User/editUserMenu";

const ChangePassword = ({ location }) => {
  const userContext = useContext(UserContext);
  const authToken = userContext.userToken;

  const [formValidation, setFormValidation] = useState({
    isVisible: false,
    isValid: true,
    message: "",
  });

  const { user } = location.state;
  const [userDetails, setUserDetails] = useState({
    oldPassword: "",
    newPassword: "",
    confirmPassword: "",
  });

  const onChange = (e) => {
    setUserDetails({ ...userDetails, [e.target.name]: e.target.value });
  };
  const onSubmit = async (e) => {
    e.preventDefault();

    const headers = {
      "Access-Control-Allow-Headers": "*", // this will allow all CORS requests
      "Access-Control-Allow-Methods": "OPTIONS,POST,GET", // this states the allowed methods
      "Content-Type": "application/json", // this shows the expected content type
      Authorization: `Bearer ${authToken}`,
    };

    const response = await Axios.post(
      "https://localhost:44353/api/User/ChangePassword",
      {
        oldPassword: userDetails.oldPassword,
        newPassword: userDetails.newPassword,
      },
      { headers: headers }
    );

    validateResponse(response.data.errorMessage);
  };

  const validateResponse = (errorMessage) => {
    if (errorMessage) {
      setFormValidation({
        isValid: false,
        isVisible: true,
        message: errorMessage,
      });
    } else {
      setFormValidation({
        isValid: true,
        isVisible: true,
        message: "Password changed successfully",
      });
    }
  };

  return (
    <div className='container-fluid '>
      <div className='row'>
        <div className='col-lg-2'>
          <EditUserMenu user={user} selected={CHANGE_PWD} />
        </div>
        <div className='col-lg-10'>
          <div className='card'>
            <div className='card-header'>Change Password</div>
            <div className='card-body'>
              <form className='form needs-validation' onSubmit={onSubmit}>
                <p className='font-weight-bold'>Old Password</p>
                <input
                  type='password'
                  value={userDetails.oldPassword}
                  onChange={onChange}
                  name='oldPassword'
                />

                <p className='font-weight-bold'>New Password</p>
                <input
                  type='password'
                  name='newPassword'
                  value={userDetails.newPassword}
                  onChange={onChange}
                />

                <p className='font-weight-bold'>Confirm Password</p>
                <input
                  type='password'
                  name='confirmPassword'
                  value={userDetails.confirmPassword}
                  onChange={onChange}
                />

                <input type='submit' value='Update' />
                <ValidationMessage
                  isVisible={formValidation.isVisible}
                  message={formValidation.message}
                  isValid={formValidation.isValid}
                />
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

ChangePassword.propTypes = {
  location: PropTypes.object.isRequired,
};

export default ChangePassword;
