// client/nt.webclient/reactjs/nt/src/pages/public/registerUser.js
import React, { useState } from "react";
import ValidationMessage from "../../components/layout/validationMessage";
import { registerUser } from "../../api/user";
import { NavLink } from "react-router-dom";
const RegisterUser = () => {
  const initialValue = {
    userName: "",
    passKey: "",
    displayName: "",
  };

  const initialValidationStatus = {
    isVisible: false,
    isValid: true,
    message: "",
  };
  const [formData, updateFormData] = useState(initialValue);
  const [userNameValidation, updateUserValidation] = useState(
    initialValidationStatus
  );
  const [passwordValidation, updatePasswordValidation] = useState(
    initialValidationStatus
  );
  const [displayNameValidation, updatedisplayNameValidation] = useState(
    initialValidationStatus
  );
  const [formValidation, updateformValidation] = useState(
    initialValidationStatus
  );

  const onChange = (e) => {
    updateFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const validateUserName = (userName) => {
    if (!userName) {
      updateUserValidation({
        isVisible: true,
        isValid: false,
        message: ["UserName cannot be empty"],
      });
      return;
    }

    if (userName.length < 6) {
      updateUserValidation({
        isVisible: true,
        isValid: false,
        message: ["UserName should be minimum 6 characters"],
      });
      return;
    }

    if (/[^0-9a-zA-Z]/.test(userName)) {
      updateUserValidation({
        isVisible: true,
        isValid: false,
        message: ["Username can include only alphanumeric characters"],
      });
      return;
    }

    updateUserValidation({ isVisible: false, isValid: true, message: "" });
  };

  const validateDisplayName = (displayName) => {
    if (!displayName) {
      updatedisplayNameValidation({
        isVisible: true,
        isValid: false,
        message: ["Display Name cannot be empty"],
      });
      return;
    }

    if (displayName.length < 2) {
      updatedisplayNameValidation({
        isVisible: true,
        isValid: false,
        message: ["Display Name should be minimum 2 characters"],
      });
      return;
    }
    updatedisplayNameValidation({
      isVisible: false,
      isValid: true,
      message: [],
    });
  };

  const validatePassword = (password) => {
    if (!password) {
      updatePasswordValidation({
        isVisible: true,
        isValid: false,
        message: ["Password cannot be empty"],
      });
      return;
    }

    if (password.length < 6) {
      updatePasswordValidation({
        isVisible: true,
        isValid: false,
        message: ["Password should be minimum 6 characters"],
      });
      return;
    }
    updatePasswordValidation({ isVisible: false, isValid: true, message: "" });
  };

  const onSubmit = async (e) => {
    e.preventDefault();

    validateUserName(formData.userName);
    validateDisplayName(formData.displayName);
    validatePassword(formData.passKey);

    if (
      userNameValidation.isValid &&
      displayNameValidation.isValid &&
      passwordValidation.isValid
    ) {
      const response = await registerUser(
        formData.userName,
        formData.displayName,
        formData.passKey
      );

      console.log(response);

      if (!response.hasError) {
        updateformValidation({
          isVisible: true,
          isValid: true,
          message: ["User is successfully registered"],
        });
      } else {
        console.log(response.error);
        updateformValidation({
          isVisible: true,
          isValid: false,
          message: response.error,
        });
      }
    }
  };
  return (
    <div className='container-fluid'>
      <div className='col-md-12 min-vh-100 d-flex flex-column justify-content-center'>
        <div className='row'>
          <div className='col-lg-4 col-md-4 mx-auto'>
            <div className='card rounded shadow shadow-sm'>
              <div className='card-header bg-primary'>
                <h3 className='mb-0'>Register</h3>
              </div>
              <div className='card-body'>
                <form className='form needs-validation' onSubmit={onSubmit}>
                  <input
                    type='text'
                    name='userName'
                    placeholder='UserName'
                    onChange={onChange}
                  />
                  <ValidationMessage
                    isVisible={userNameValidation.isVisible}
                    message={userNameValidation.message}
                    isValid={userNameValidation.isValid}
                  />
                  <input
                    type='text'
                    name='displayName'
                    placeholder='Display Name'
                    onChange={onChange}
                  />
                  <ValidationMessage
                    isVisible={displayNameValidation.isVisible}
                    message={displayNameValidation.message}
                    isValid={displayNameValidation.isValid}
                  />
                  <input
                    type='password'
                    name='passKey'
                    placeholder='Password'
                    onChange={onChange}
                  />
                  <ValidationMessage
                    isVisible={passwordValidation.isVisible}
                    message={passwordValidation.message}
                    isValid={passwordValidation.isValid}
                  />
                  <input
                    type='submit'
                    value='Sign Up'
                    className='bg-primary btn-block'
                  />
                  <div>
                    <NavLink to="/">Sign in</NavLink>
                  </div>
                  <ValidationMessage
                    isVisible={formValidation.isVisible}
                    message={formValidation.message}
                    isValid={formValidation.isValid}
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default RegisterUser;

// client/nt.webclient/vue3/nt/src/components/public/RegisterUser.vue
<template>
  <div class="card card-block rounded shadow shadow-sm" >
    <div class="card-header bg-primary text-light text-uppercase">
      <div class="card-title align-middle">
        <h5 class="mb-0">Sign Up</h5>
      </div>
    </div>
    <div class="card-body">
      <form class="form needs-validation" @submit.prevent="onSubmit">
        <div class="form-group">
          <input
            type="text"
            v-model="userName"
            class="form-control block"
            placeholder="Username"
          />
        </div>
        <div class="d-flex justify-content-left" v-if="v$.userName.$error">
        <ValidationMessage   :messages="v$.userName.$errors.map(x=>x.$message)"
            v-bind:isError="true"
          />
        </div>
        <div class="form-group">
          <input
            type="password"
            v-model="password"
            class="form-control block"
            placeholder="Password"
          />
        </div>
        <div class="d-flex justify-content-left" v-if="v$.password.$error">
        <ValidationMessage   :messages="v$.password.$errors.map(x=>x.$message)"
            v-bind:isError="true"
          />
        </div>
        <div class="form-group">
          <input
            type="password"
            v-model="confirmPassword"
            class="form-control block"
            placeholder="Confirm Password"
          />
        </div>
        <div class="d-flex justify-content-left" v-if="v$.confirmPassword.$error">
        <ValidationMessage   :messages="v$.confirmPassword.$errors.map(x=>x.$message)"
            v-bind:isError="true"
          />
        </div>

        <div class="form-group">
          <input
            type="submit"
            class="btn btn-block btn-primary"
            value="Submit"
          />
        </div>
      </form>
      <div>
        Already a member ?
        <router-link to="/">Sign in here</router-link>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";
import ValidationMessage from "@/components/generic/ValidationMessage";
import { useVuelidate } from '@vuelidate/core'
import { required, minLength,sameAs, helpers  } from '@vuelidate/validators'
import {registerUser} from "@/api/user.js"

const userName = ref("");
const password = ref("");
const confirmPassword = ref("");
const $externalResults = ref({})


const rules = computed(()=>({
  userName : {
                required:helpers.withMessage('Username cannot be empty', required), 
                minLengthValue: helpers.withMessage('Username should minimum 4 characters',minLength(4)) 
             },
  password : 
            {
              required:helpers.withMessage('Password cannot be empty', required),  
              minLengthValue: helpers.withMessage('Password should minimum 4 characters',minLength(4)) 
            },
  confirmPassword : { sameAsPassword: helpers.withMessage('Password do not match', sameAs(password))}
}))

const v$ = useVuelidate(rules,{userName,password,confirmPassword},{ $externalResults});

const onSubmit = async () => {
 
  v$.value.$clearExternalResults();
  var validationResult = await v$.value.$validate();
  if (!validationResult) {
        console.log("Validation failed");
        return;
      }
      const response = await registerUser(userName.value,'',password.value);

      if(response.hasError){
        // error
      }
      else{
        const errors = {
        userName : ['user created successfully']
       };
        $externalResults.value = errors;
      }


}



</script>

<style></style>
