// nt.webclient/reactjs/nt/src/pages/private/movie/createMovie.js
import React, { useState, useContext } from "react";
import UserContext from "../../../context/user/userContext";
import Calender from "../../../components/layout/calender";
import DynamicTextBox from "../../../components/layout/dynamicTextBox";
import axios from "axios";
import ValidationMessage from "../../../components/layout/validationMessage";

const CreateMovie = () => {
  const currentUser = useContext(UserContext);
  const authToken = currentUser.userToken;

  const [formValidation, setFormValidation] = useState({
    isVisible: false,
    isValid: true,
    message: "",
  });

  const [movieMetadata, setMovieMetadata] = useState({
    title: "",
    language: "",
    releaseDate: new Date(),
    actors: [],
  });

  const [errors, setErrors] = useState([]);

  const onChange = (e) => {
    setMovieMetadata({ ...movieMetadata, [e.target.name]: e.target.value });
  };

  const onReleaseDateChange = (date) => {
    setMovieMetadata({ ...movieMetadata, releaseDate: date });
  };

  const onActorCollectionChange = (newCollection) => {
    console.log(newCollection);
    setMovieMetadata({
      ...movieMetadata,
      actors: newCollection.map((actor) => actor.text),
    });
  };

  const hasError = (key) => errors.indexOf(key) !== -1;

  const onSubmit = async (e) => {
    e.preventDefault();
    console.log(errors);
    setErrors([]);
    let tempErrors = errors;
    // TODO : Validate
    if (movieMetadata.title === "") {
      tempErrors = [...tempErrors, "title"];
    }
    if (movieMetadata.language === "") {
      tempErrors = [...tempErrors, "language"];
    }

    setErrors(tempErrors);

    if (tempErrors.length > 0) {
      return false;
    } else {
      const headers = {
        "Access-Control-Allow-Headers": "*", // this will allow all CORS requests
        "Access-Control-Allow-Methods": "OPTIONS,POST,GET", // this states the allowed methods
        "Content-Type": "application/json", // this shows the expected content type
        Authorization: `Bearer ${authToken}`,
      };

      const response = await axios.post(
        "https://localhost:44353/api/Movie/CreateMovie",
        movieMetadata,
        { headers: headers }
      );

      validateResponse(response.data.errorMessage);
    }
  };

  const validateResponse = (errorMessage) => {
    if (errorMessage) {
      setFormValidation({
        isValid: false,
        isVisible: true,
        message: errorMessage,
      });
    } else {
      setFormValidation({
        isValid: true,
        isVisible: true,
        message: "Movie created successfully",
      });
    }
  };

  return (
    <div className='container-fluid'>
      <div className='row'>
        <div className='col-lg-12'>
          <form onSubmit={onSubmit}>
            <input
              type='text'
              name='title'
              className={
                hasError("title") ? "form-control is-invalid" : "form-control"
              }
              placeholder='Movie Title'
              onChange={onChange}
            />
            <div className={hasError("title") ? "invalid-feedback" : "d-none"}>
              Please enter a movie title
            </div>
            <input
              type='text'
              name='language'
              className={
                hasError("language")
                  ? "form-control is-invalid"
                  : "form-control"
              }
              placeholder='Language'
              onChange={onChange}
            />
            <div
              className={hasError("language") ? "invalid-feedback" : "d-none"}
            >
              Please enter language
            </div>
            <Calender
              title='Release Date'
              onChange={(date) => onReleaseDateChange(date)}
              value={movieMetadata.releaseDate}
            />
            <DynamicTextBox
              defaultText='Actor'
              collection={[{ text: "Aamir Khan" }]}
              onCollectionChange={onActorCollectionChange}
              buttonTitle='Add Actor'
            />

            <input type='submit' value='Create Movie' />
            <ValidationMessage
              isVisible={formValidation.isVisible}
              message={formValidation.message}
              isValid={formValidation.isValid}
            />
          </form>
        </div>
      </div>
    </div>
  );
};

export default CreateMovie;

// client/nt.webclient/vuejs/nt/src/pages/private/movie/CreateMovie.vue
<template>
  <div class="container-fluid">
    <div class="row align-items-center justify-content-center">
      <div class="col-sm-12 col-md-10 col-lg-8">
        <div class="card">
          <div class="card-header font-weight-bold text-uppercase">
            Create Movie
          </div>
          <div class="card-body">
            <form
              class="form-horizontal needs-validation"
              v-on:submit="onSubmit"
            >
              <div class="form-group">
                <label for="movieTitle">Movie Title</label>
                <input
                  type="text"
                  placeholder="Movie Title"
                  name="movieTitle"
                  v-model="title"
                  v-bind:class="
                    hasError('title')
                      ? 'form-control block is-invalid'
                      : 'form-control block'
                  "
                />
              </div>
              <div class="form-group">
                <label for="language">Language</label>
                <input
                  type="text"
                  v-model="language"
                  name="language"
                  placeholder="Language"
                  v-bind:class="
                    hasError('language')
                      ? 'form-control block is-invalid'
                      : 'form-control block'
                  "
                />
              </div>
              <div class="form-group">
                <label for="releaseDate">Release Date</label>
                <v-date-picker v-model="releaseDate">
                  <template v-slot="{ inputValue, inputEvents }">
                    <input
                      v-bind:class="
                        hasError('tags')
                          ? 'form-control block is-invalid'
                          : 'form-control block'
                      "
                      :value="inputValue"
                      v-on="inputEvents"
                    />
                  </template>
                </v-date-picker>
              </div>
              <div class="form-group">
                <label for="tags">Cast And Crew</label>
                <input
                  v-model="tags"
                  placeholder="Cast And Crew"
                  name="tags"
                  v-bind:class="
                    hasError('tags')
                      ? 'form-control block is-invalid'
                      : 'form-control block'
                  "
                />
              </div>
              <div class="form-group">
                <input type="submit" value="Save Changes" class="btn-primary" />
              </div>
              <div v-bind:class="showServerMessage()">
                <ul>
                  <li v-for="(error, index) in serverMessage" :key="index">
                    <small>{{ error }}</small>
                  </li>
                </ul>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { createMovie } from "../../../api/movies";

export default {
  name: "CreateMovie",
  data() {
    return {
      title: "",
      releaseDate: new Date(),
      language: "",
      tags: "",
      errors: [],
      serverMessage: [],
      hasServerError: false,
    };
  },
  methods: {
    async onSubmit(e) {
      e.preventDefault();
      if (!this.validateForm()) {
        console.log(this.errors);
        console.log("Form is INVALID");
        return;
      }

      var movie = {
        title: this.title,
        language: this.language,
        releaseDate: this.releaseDate,
        actors: this.tags.split(","),
      };
      var response = await createMovie(movie);
      if (response.hasError) {
        this.hasServerError = true;
        this.serverMessage = response.error;
        return;
      }
      this.serverMessage.push("Movie created successfully");
    },
    hasError(key) {
      return this.errors.indexOf(key) != -1;
    },
    showServerMessage() {
      if (!this.serverMessage.length) {
        return "d-none";
      }

      return this.hasServerError
        ? "text-danger text-left"
        : "text-success text-left";
    },
    validateForm() {
      let isValidFlag = true;
      this.errors = [];

      if (!this.title) {
        this.errors.push("title");
        isValidFlag = false;
      }

      if (!this.releaseDate) {
        this.errors.push("releaseDate");
        isValidFlag = false;
      }

      if (!this.language) {
        this.errors.push("language");
        isValidFlag = false;
      }

      return isValidFlag;
    },
  },
};
</script>

<style scoped>
.form-group {
  align-items: left;
}
.form-group label {
  text-align: left;
  float: left;
}

.form-group small {
  text-align: center;
  float: none;
}
</style>
